services:
  github_pages:
    image: madduci/docker-github-pages
    ports:
      - "4000:4000"
    volumes:
      - .:/site
    entrypoint: /bin/sh
    command: -c "bundle install && bundle exec jekyll serve --watch --force_polling --host 0.0.0.0"
